//package com.bizmate.groupware.service;
//
//import com.bizmate.groupware.approval.domain.ApprovalDocuments;
//import com.bizmate.groupware.approval.domain.ApprovalStatus;
//import com.bizmate.groupware.approval.dto.ApprovalDocumentsDto;
//import com.bizmate.groupware.approval.repository.ApprovalDocumentsRepository;
//import com.bizmate.groupware.approval.service.ApprovalDocumentsService;
//import com.fasterxml.jackson.core.JsonProcessingException;
//import org.junit.jupiter.api.Test;
//import org.springframework.beans.factory.annotation.Autowired;
//import org.springframework.boot.test.context.SpringBootTest;
//import org.springframework.transaction.annotation.Transactional;
//
//import java.util.List;
//
//import static org.assertj.core.api.Assertions.assertThat;
//
//@SpringBootTest
//@Transactional
//public class ApprovalDocumentsServiceIntegrationTests {
//
//    @Autowired
//    private ApprovalDocumentsService approvalDocumentsService;
//
//    @Autowired
//    private ApprovalDocumentsRepository approvalDocumentsRepository;
//
//    @Test
//    public void createNewDocument_withAutoGeneratedId() throws JsonProcessingException {
//        // given
//        ApprovalDocumentsDto dto = ApprovalDocumentsDto.builder()
//                .title("인사발령 보고서")
//                .docType("보고서")
//                .departmentCode("HR")   // 부서 코드 → ID 생성기에서 사용됨
//                .userId(1001L)
//                .roleId(10L)
//                .empId(220250428L)
//                .docContent(List.of(
//                        // 본문 JSON
//                        new java.util.HashMap<String, Object>() {{
//                            put("title", "인사발령");
//                            put("text", "2025년 10월 5일자 인사발령 건입니다.");
//                        }}
//                ))
//                .approvalLine(List.of(
//                        // 결재선 JSON
//                        new java.util.HashMap<String, Object>() {{
//                            put("approverId", "안재성");
//                            put("order", 1);
//                        }},
//                        new java.util.HashMap<String, Object>() {{
//                            put("approverId", "한유주");
//                            put("order", 2);
//                        }}
//                ))
//                .build();
//
//        // when
//        ApprovalDocumentsDto saved = approvalDocumentsService.createNewDocument(dto);
//
//        // then
//        System.out.println("Generated Document ID: " + saved.getId());
//        System.out.println("Status: " + saved.getStatus());
//        System.out.println("CreatedAt: " + saved.getCreatedAt());
//
//        assertThat(saved.getId()).startsWith("HR-"); // HR 부서코드가 포함된 ID
//        assertThat(saved.getStatus()).isEqualTo(ApprovalStatus.PENDING.name());
//        assertThat(saved.getTitle()).isEqualTo("인사발령 보고서");
//
//        // DB 저장 확인
//        ApprovalDocuments entity = approvalDocumentsRepository.findById(saved.getId()).orElseThrow();
//        assertThat(entity.getDocId()).isEqualTo(saved.getId());
//    }
//}